constructCategoryTrainingStimulus(trainingStimuli{10}(:,1));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,2));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,3));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,4));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,5));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,6));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,7));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,8));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,9));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,10));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,11));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,12));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,13));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,14));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,15));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,16));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,17));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{10}(:,18));